Valor limite para poros azuis como argumento da chamada do med2image. Rotação de 90 graus desabilitada
Chamada do run_seg_med2image com 'flags' em vez de argumentos posicionais. Espelhamento da amostra desabilitado (a verificar, pelo menos houve a rotação). Intervalo de valores mapeados em cor azul usa valor enviado pela chamada do run_seg_med2image

diff --git a/bin/run_seg_med2image b/bin/run_seg_med2image
--- a/bin/run_seg_med2image
+++ b/bin/run_seg_med2image
@@ -1,23 +1,76 @@
 #!/bin/bash
-if [ $# -lt 3 ] || [ $# -gt 4 ]
- then
-   echo "Chamada do med2image modificado para projecoes com cor"
-   echo "[Erro] Deve usar 3 ou 4 argumentos de entrada"
-   echo "Uso do programa: $0 <path/to/file.nii> <path/to/folder> <PROJ_TYPE> [path/to/colormap.txt]"
-   exit 1
+while [ $# -gt 0 ]
+do
+key="$1"
+
+case $key in
+    -i|--inputFile)
+    input_file="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -d|--outputDir)
+    out_dir="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    --type)
+    proj_type="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -c|--colorTxt)
+    colormap="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    --blueLimit)
+    blueLimit="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    *)    # unknown option
+  	echo "Chamada do med2image modificado para projecoes com cor - Opcao invalida: $1"
+  	echo "Uso do programa: $0 -i|--inputFile <path/to/file.nii> -d|--outputDir <path/to/folder> [--type <PROJ_TYPE>] [-c|--colorTxt path/to/colormap.txt] [--blueLimit 0-255]"
+    exit 1
+    ;;
+esac
+done
+
+if [ -z "$input_file" ] | [ -z "$out_dir" ]
+then
+	missingArgs=""
+	if [ -z "$input_file" ]
+	then missingArgs="$missingArgs input_file"
+	fi
+	if [ -z "$out_dir" ]
+	then missingArgs="$missingArgs out_dir"
+	fi
+    echo "Chamada do med2image modificado para projecoes com cor - 1 ou mais argumentos obrigatorios faltando: $missingArgs "
+  	echo "Uso do programa: $0 -i|--inputFile <path/to/file.nii> -d|--outputDir <path/to/folder> [--type <PROJ_TYPE>] [-c|--colorTxt path/to/colormap.txt] [--blueLimit 0-255]"
+    exit 1
+fi
+echo "input_file  $input_file"
+echo "out_dir  $out_dir"
+echo "proj_type  $proj_type"
+echo "colormap  $colormap"
+echo "blueLimit  $blueLimit"
+
+if [ -z "$proj_type" ]
+then proj_type="Projecao_Tomografica"
 fi
 
-input_file=$1
-out_dir=$2
-proj_type=$3
-colormap_call=""
-
-if [ $# -eq 4 ]; then #nao enviou colormap.txt
-   colormap_call="-c $4"
-   echo "Usando arquivo de colormap $4"
+if [ -z "$colormap" ]
+then colormap_call=""
+else colormap_call="-c $colormap"
 fi
 
-. ~/med2image_venv/bin/activate 
+if [ -z "$blueLimit" ]
+then bluelimit_call=""
+else bluelimit_call="--blueLimit $blueLimit"
+fi
+
+. ~/med2image_venv/bin/activate
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-$DIR/med2image -i $input_file -d $out_dir -t png -r --type $proj_type $colormap_call #-s 500 # -s m/<int sliceNumber> soh pra testes (converte soh o slice do meio)
+$DIR/med2image -i $input_file -d $out_dir -t png -r --type $proj_type $colormap_call $bluelimit_call -s m #-s 500 # -s m/<int sliceNumber> soh pra testes (converte soh o slice do meio)
